### ISSUE TITLE
Remove quotes

### ISSUE THREAD

**Issue by ai** [archana-s/postcss-flexbox#2]
CSS do not have quotes in standard properties. So mayb instead of:

``` css
.horizontal-box.align-items-center {
   box: 'horizontal center';
}
```

we should have:

``` css
.horizontal-box.align-items-center {
   box: horizontal center;
}
```
